apiVersion: v1
kind: ConfigMap
metadata:
  name: scm-config
  namespace: {{ .Values.namespace }}
data:
  NACOS_SERVER: {{ .Values.env.nacosServer }}
  DB_HOST: {{ .Values.env.dbHost }}
  DB_PORT: {{ .Values.env.dbPort }}
  REDIS_HOST: {{ .Values.env.redisHost }}
  REDIS_PORT: {{ .Values.env.redisPort }}
