apiVersion: v1
kind: Secret
metadata:
  name: scm-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.secrets.dbUsername | default "YWRtaW4=" | b64enc }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | default "YWRtaW4xMjM=" | b64enc }}
